name: invalid
description: A new Flutter package project.
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.3
  equatable: ^1.2.5
  intl: ^0.16.1
  flutter_bloc: ^6.0.5

dev_dependencies:
  bloc_test: ^7.0.4
  flutter_test:
    sdk: flutter